# This rule is not used by the project foo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over example.codecrafts.cf.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: foo-operator
    app.kubernetes.io/managed-by: kustomize
  name: foomanager-admin-role
rules:
- apiGroups:
  - example.codecrafts.cf
  resources:
  - foomanagers
  verbs:
  - '*'
- apiGroups:
  - example.codecrafts.cf
  resources:
  - foomanagers/status
  verbs:
  - get
