---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - example.codecrafts.cf
  resources:
  - foomanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.codecrafts.cf
  resources:
  - foomanagers/finalizers
  verbs:
  - update
- apiGroups:
  - example.codecrafts.cf
  resources:
  - foomanagers/status
  verbs:
  - get
  - patch
  - update
