apiVersion: example.codecrafts.cf/v1
kind: FooManager
metadata:
  labels:
    app.kubernetes.io/name: foo-operator
    app.kubernetes.io/managed-by: kustomize
  name: foomanager-sample
spec:
  # TODO(user): Add fields here
